### ISSUE TITLE
Ограничить максимальное количество тегов и длину тега

### ISSUE THREAD

**Issue by kuduzow** [intocode/iqa-frontend#312]
## Какую фичу ты предлагаешь?

Ограничить максимальное количество тегов и длину тега

## Какую пользу принесет эта фича?

Сейчас можно добавлять любое количество тегов при публикации вопроса, а также можно добавлять тег любой длины. Отсутствие таких ограничений может позволить пользователям злоупотребить этой фичей, к примеру добавить очень длинный тег, который испортит вёрстку главной страницы.

<img width="878" alt="Screenshot 2023-01-28 at 00 40 49" src="https://user-images.githubusercontent.com/2021604/215206125-72bb1690-0da8-46fc-b3ff-ade95f29ceb5.png">

Рекомендую ограничить макс. количество тегов числом 5, а максимальное кол-во символов в сделать 15. Числа вынести в отдельные константы в `/app/constants.js`, чтобы в будущем было легко их изменять.

**Comment by SaydAliUsmanov** [comment]
@kuduzow в хидере не отображается кнопка создания вопроса. Я подразумеваю, что эти самые теги находятся на странице создания вопроса. Мне нужен какой-то особый доступ?

**Comment by kuduzow** [comment]
Нужно быть авторизованным, чтобы видеть кнопку добавления

**Comment by SaydAliUsmanov** [comment]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/90183233/215292700-ac866ef8-e930-48b5-bf6a-333df9166ea1.png">

Я авторизован, но не показывает кнопку добавления вопроса. Как я заметил и других фич тоже нет, например лайки. Видимо для включения этих фич нужен env файл, т.к на проде все фичи доступны, а на локалке - нет

**Comment by kuduzow** [comment]
Кстати да, вот `.env`-файл для включения всех фич:

```
REACT_APP_FEATURE_SEARCH=on
REACT_APP_FEATURE_ADD_QUESTION=on
REACT_APP_FEATURE_FAVORITES=on
REACT_APP_FEATURE_DELETE_QUESTION=on
REACT_APP_FEATURE_TAGS=on
REACT_APP_FEATURE_COMMENTARIES=on
REACT_APP_FEATURE_RATING=on
REACT_APP_FEATURE_LIKE_COMMENT=on
```
