### ISSUE TITLE
Если последний комментарий будет слишком длинным, на главной странице будет отображаться не очень красиво

### ISSUE THREAD

**Issue by baysarov077** [intocode/iqa-frontend#327]
<img width="884" alt="Снимок экрана 2023-02-23 в 15 42 46" src="https://user-images.githubusercontent.com/98719246/220911022-4232409f-3b3d-44d1-8163-eb7eff9e1e91.png">

**Comment by kuduzow** [comment]
Да, нужно срезать символы, при этом не обрезая слово целиком.

Думаю можно поставить максимум 140 символов, но вынести это значение в константу, чтобы потом не искать когда захотим изменить
