### ISSUE TITLE
Исправить баг с счетчиком просмотров поста

### ISSUE THREAD

**Issue by baysarov077** [intocode/iqa-frontend#347]
## Описание бага

После того как перейти на страницу определенного вопроса и вернуться на главную, счетчик регистрирует +2 просмотр

## Как можно увидеть этот баг?

Зайти на главную страницу, перейти к вопросу и обратно вернуться на главную

https://user-images.githubusercontent.com/98719246/221183707-35d7719b-d3a4-40ec-af13-7fe3dfe9221d.MP4

**Comment by brz95** [comment]
такой проблемы не наблюдается.

**Comment by kuduzow** [comment]
> такой проблемы не наблюдается. не удается воспроизвести.

да, у меня тоже нормально выводится. Немного подождем еще, если точно не повторяется, то закроем issue

**Comment by kuduzow** [comment]
Баг не повторяется на стейдже и проде
