### ISSUE TITLE
При наведении мыши на текст "Обсуждение"/иконку<Обсуждение> появляется стрелка выделения вместо стрелки с пальцем

### ISSUE THREAD

**Issue by soltamuradov** [intocode/iqa-frontend#352]
## Описание бага
При наведении мыши на текст "Обсуждение"/иконку<Обсуждение> появляется стрелка выделения вместо стрелки с пальцем

## Как можно увидеть этот баг?

Выполнить следующие шаги:
1. Открыть приложение.
2. Навести на текст "Обсуждение"/иконку<Обсуждение> мышью у любого вопроса на десктопе

## Что должно было случиться?
Появляется стрелка с выделением текста
![2023-02-24 18 5633 06](https://user-images.githubusercontent.com/82868823/221226203-c4fa3734-d039-437e-b0ef-2a85e9282c07.jpg)

Опиши что ты ожидал увидеть вместо ошибки выполнив эти шаги
Появляется стрелка с указательным пальцем
![2023-02-24 18 55 41](https://user-images.githubusercontent.com/82868823/221226238-c7223510-e5fd-4707-a3f9-304385d1e71e.jpg)

**Comment by kuduzow** [comment]
Исправлено в ПР https://github.com/intocode/iqa-frontend/pull/334
